### ISSUE TITLE
MemoryError for run of 3300 x 3000 genes

### ISSUE THREAD

**Issue by timdiels** [timdiels/coexpnetviz-python#18]
In GitLab by @timdiels on Jul 18, 2019, 11:12

User mail forwarded to me by ortzf:

> We tried to run CoExpNetViz web server for 3000 genes and it shows memory error.

```
/www/group/biocomp/extra/morph/production/install/venv/lib/python3.5/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
/www/group/biocomp/extra/morph/production/install/venv/lib/python3.5/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
Cytoscape input.txt: 5th percentile = -0.2624406058826883
Cytoscape input.txt: 95th percentile = 0.5735227522639331
Traceback (most recent call last):
  File "/www/group/biocomp/extra/morph/production/install/venv/bin/dbg-coexpnetviz", line 9, in 
    load_entry_point('deep-blue-genome==2.0.0.dev2', 'console_scripts', 'dbg-coexpnetviz')()
  File "/www/group/biocomp/extra/morph/production/install/venv/lib/python3.5/site-packages/deep_blue_genome/coexpnetviz/main.py", line 48, in main
    main_(sys.argv)
  File "/www/group/biocomp/extra/morph/production/install/venv/lib/python3.5/site-packages/deep_blue_genome/coexpnetviz/main.py", line 108, in main_
    network = coexpnetviz(baits, gene_families, expression_matrices, correlation_method, [args.lower_percentile_rank, args.upper_percentile_rank])
  File "/www/group/biocomp/extra/morph/production/install/venv/lib/python3.5/site-packages/deep_blue_genome/coexpnetviz/algorithm.py", line 156, in coexpnetviz
    bait_corrs = corrs.loc[baits_]
  File "/www/group/biocomp/extra/morph/production/install/venv/lib/python3.5/site-packages/pandas/core/indexing.py", line 1296, in __getitem__
    return self._getitem_axis(key, axis=0)
  File "/www/group/biocomp/extra/morph/production/install/venv/lib/python3.5/site-packages/pandas/core/indexing.py", line 1456, in _getitem_axis
    return self._getitem_iterable(key, axis=axis)
  File "/www/group/biocomp/extra/morph/production/install/venv/lib/python3.5/site-packages/pandas/core/indexing.py", line 1098, in _getitem_iterable
    result = self.obj.take(indexer, axis=axis, convert=False)
  File "/www/group/biocomp/extra/morph/production/install/venv/lib/python3.5/site-packages/pandas/core/generic.py", line 1633, in take
    convert=True, verify=True)
  File "/www/group/biocomp/extra/morph/production/install/venv/lib/python3.5/site-packages/pandas/core/internals.py", line 3711, in take
    axis=axis, allow_dups=True)
  File "/www/group/biocomp/extra/morph/production/install/venv/lib/python3.5/site-packages/pandas/core/internals.py", line 3597, in reindex_indexer
    for blk in self.blocks]
  File "/www/group/biocomp/extra/morph/production/install/venv/lib/python3.5/site-packages/pandas/core/internals.py", line 3597, in 
    for blk in self.blocks]
  File "/www/group/biocomp/extra/morph/production/install/venv/lib/python3.5/site-packages/pandas/core/internals.py", line 996, in take_nd
    allow_fill=True, fill_value=fill_value)
  File "/www/group/biocomp/extra/morph/production/install/venv/lib/python3.5/site-packages/pandas/core/algorithms.py", line 930, in take_nd
    out = np.empty(out_shape, dtype=dtype)
```

> Additionally we also tried installing command line interface of CoExpNetViz with Python 2.7 as well as Python 3.7.3; but obtained the following error: 

```
Error: could not find a version that satisfies the requirement coexpnetviz from version: none 
Error: No matching distribution found for Coexpnetviz
```

Input:

- Baits: [genes.txt](/uploads/9353d4d6d7412a5a3dd1f7a54ccb6cd8/genes.txt)
- Exp mats: [Cytoscape_input.txt](/uploads/f710aff64cbdafef3444ba020c22f01f/Cytoscape_input.txt)
- Defaults otherwise

**Comment by timdiels** [comment]
In GitLab by @timdiels on Jul 18, 2019, 11:13

made the issue confidential

**Comment by timdiels** [comment]
In GitLab by @timdiels on Jul 18, 2019, 11:14

Making confidential because user submitted files may be confidential and this isn't a private repo.

**Comment by timdiels** [comment]
In GitLab by @timdiels on Jul 18, 2019, 11:15

Files have no double tabs, no trailing/leading whitespace, no empty lines, no non-tab whitespace. Seems this is purely due to not having enough memory. I tried running with medium queue h_vmem=20G, but MemoryError.

**Comment by timdiels** [comment]
In GitLab by @timdiels on Jul 18, 2019, 11:22

Simply instantiating `np.ones(110*3306*3000)` eats up roughly 8GB of memory on my machine, it simply is a large input. I'm not sure whether rewriting part of the code to more memory-efficient python-ish langs or even Rust would help; however dropping pandas may yield an improvement in mem usage; we'd have to profile.

Retried with 30G, I'm not sure whether it actually got the 30G, maybe I'm just requesting more than the queue is willing to give. Tried with 300G and it crashed shortly after reaching 500MB mem so probably it's not getting the ludicrous 300G amount or even the 20G. Retried with long queue, even there it seems to be limited by 500MB mem (there's some lag on reporting stats, so the actual limit could be higher, especially as instantiating the np array can happen pretty fast)

long@webcls01 queue seems able to have more memory though (`qstat -F`):

```
        hl:mem_free=245.953G
        hl:swap_free=8.000G
        hl:virtual_free=253.953G
        qf:s_rt=20:00:00
        qf:h_rt=infinity
        qf:s_cpu=infinity
        qf:h_cpu=infinity
        qf:s_fsize=infinity
        qf:h_fsize=infinity
        qf:s_data=infinity
        qf:h_data=infinity
        qf:s_stack=infinity
        qf:h_stack=infinity
        qf:s_core=infinity
        qf:h_core=infinity
        qf:s_rss=infinity
        qf:h_rss=infinity
        qf:s_vmem=infinity
        qf:h_vmem=infinity
```

Even short queue, the only difference between short, medium and long seems to be the max allowed runtime. Even trying with a 'reasonable' 200G, it still crashes early; but it might be requesting >200GB mem in one alloc, but that's way above my calculations. Ideally should add print statements to the code to debug how much it is requesting, how much it is using at the time... It seems that adding `-l h_vmem=200G` is unnecessary as the default seems to be no mem-limit at all. I'll also use the medium queue again as that should be plenty.

**Comment by timdiels** [comment]
In GitLab by @timdiels on Jul 18, 2019, 11:52

Another way of reducing mem footprint, if necessary, if that's the issue, is to see if the alg can redesigned. Perhaps we calculate in chunks.

**Comment by timdiels** [comment]
In GitLab by @timdiels on Jul 29, 2019, 17:19

thpar ran it on BITS server, oddly it did not need much memory at all. The plain text correlation matrix file was roughly 250MB. I managed to get my local coexpnetviz going again as well, to run jobs like these:

```
workon coexpnetviz
cd ~/projects/varbio
git checkout 2.0.0
cd ~/projects/coexpnetviz3
git checkout 7986164f35dc982fbb1aaae1bdf301149f7d6939  # maybe we can tag this 2.0.0.dev0 or so?
pip install -e ../varbio
pip install -e .
# if pip install fails, first retry both; worst case start with a fresh virtualenv
coexpnetviz --help  # should work now
```

**Comment by timdiels** [comment]
In GitLab by @timdiels on Jul 29, 2019, 17:19

closed
